### ISSUE TITLE
Local LLMs

### ISSUE THREAD

**Issue by veryvanya** [jbpayton/llm-auto-forge#1]
Any chance of integrating local LLMs through GPT4ALL, Oogabooga, LocalAI or connect to different model APIs (Claude)?

**Comment by jbpayton** [comment]
Thanks and stay tuned (I am AFK for a couple of days) The lowest lying fruit for me would be allowing the user to specify models for the lower level elements. This would allow everything compatible with the Langchain chat API to interoperable. 

However your mileage may very as I will not likely have the capability to test them all, as right now, the only local model that I know of that is capable of “agentic behavior” is llama 70b. In terms of online hosted models Claude 2 should be good.

**Comment by jbpayton** [comment]
I removed the typing hints for OpenAI llms. While the examples still use them, other models could be used, provided that they implmented chat specific elements. While this doesnt directly address OogaBooga, you should be able to make use of langchain's GPT4All, and other model integrations (see list [here ](https://python.langchain.com/docs/integrations/llms/)) - of course, your mileage may vary as to how much success you will have, due to the lack of emergent agentic behavior in some of the simpler models.

**Comment by jbpayton** [comment]
Closed, however, if this continues to trip people up, I may need to migrate to something other than langchain in the medium/long term.

**Comment by jmanhype** [comment]
flowise

> Closed, however, if this continues to trip people up, I may need to migrate to something other than langchain in the medium/long term.

flowise
